# sentiment analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

import re
from textblob import TextBlob

In [19]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\Sehar
[nltk_data]     Khan\AppData\Roaming\nltk_data...


True

In [20]:
# importing csv file

df = pd.read_csv('Data AnalystTest DataUS.csv')

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Sehar
[nltk_data]     Khan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [114]:
df.head()

Review        date  \
0  I was very impressed with the resort.\n Great ...  2019/08/20   
1  The rooms were nice the outside needs work als...  2019/08/20   
2  Great location! I have stayed at this hotel on...  2019/08/20   
3  The hotel was adequate for my stay. The strips...  2019/08/20   
4  Great location, room was large and spacious. P...  2019/08/19   

   polarity_scores  
0           0.9421  
1           0.8360  
2           0.6588  
3           0.3634  
4           0.9260

In [115]:
df.describe()

polarity_scores
count        33.000000
mean          0.543521
std           0.442306
min          -0.801600
25%           0.510600
50%           0.708800
75%           0.807400
max           0.942100

In [138]:
pd.isnull(df).sum()

Review               55
date                  0
polarity_scores    6415
dtype: int64

In [141]:
df.drop(['polarity_scores'], axis = 1 , inplace = True)

In [146]:
pd.isnull(df).sum()

Review    0
date      0
dtype: int64

In [145]:
df.dropna(inplace=True)

In [117]:
df.shape

(6448, 3)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6448 entries, 0 to 6447
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Review           6393 non-null   object 
 1   date             6448 non-null   object 
 2   polarity_scores  33 non-null     float64
dtypes: float64(1), object(2)
memory usage: 151.3+ KB


In [27]:
df['Review'] = df['Review'].astype('object')

In [120]:
df.head()

Review        date  \
0  I was very impressed with the resort.\n Great ...  2019/08/20   
1  The rooms were nice the outside needs work als...  2019/08/20   
2  Great location! I have stayed at this hotel on...  2019/08/20   
3  The hotel was adequate for my stay. The strips...  2019/08/20   
4  Great location, room was large and spacious. P...  2019/08/19   

   polarity_scores  
0           0.9421  
1           0.8360  
2           0.6588  
3           0.3634  
4           0.9260

In [121]:
df['Review'].values[0]

'I was very impressed with the resort.\n Great staff at the main resort pool bar! We had a blast with them.\n Clean, professional staff, great location and very reasonable!\n  \n  Read more\n  Read less'

In [122]:
df['date'].value_counts().sort_index()

2018/08/01     11
2018/08/02      7
2018/08/03     11
2018/08/04      7
2018/08/05     12
             ... 
Mar 2019       35
May 2019      121
Nov 2018       42
Oct 2018       58
Sep 2018       35
Name: date, Length: 403, dtype: int64

In [123]:
df['date'].value_counts()

Jun 2019      145
May 2019      121
Jul 2019       92
2018/12/01     66
Oct 2018       58
             ... 
2018/09/28      3
2019/06/06      2
Dec 2018        2
2019/05/31      2
2019/06/08      2
Name: date, Length: 403, dtype: int64

In [124]:
example = df['Review'][4898]
print(example)

Friendly staff, excellent location. Would stay again in an instant.
  
  Read more
  Read less


In [95]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm


sia = SentimentIntensityAnalyzer


In [107]:
sia().polarity_scores(example)

In [136]:
df.head(35)

Review        date  \
0   I was very impressed with the resort.\n Great ...  2019/08/20   
1   The rooms were nice the outside needs work als...  2019/08/20   
2   Great location! I have stayed at this hotel on...  2019/08/20   
3   The hotel was adequate for my stay. The strips...  2019/08/20   
4   Great location, room was large and spacious. P...  2019/08/19   
5   All the options for fun were great! Do wish th...  2019/08/19   
6   Old. Musty. Motel. \n Bath need an update asap...  2019/08/19   
7   Loved the layout of the hotel and the relaxing...  2019/08/19   
8   My wife and I loved everything about it. It’s ...  2019/08/19   
9   rooms were very small, was told i had a compli...  2019/08/19   
10  Very clean and friendly and I love the locatio...  2019/08/19   
11  Nice and comfortable good position near the st...  2019/08/19   
12  Location was great, lobby area was nice but ro...  2019/08/19   
13  Quiet and at a great location. \n Good control...  2019/08/19   
14  El servicio super amables no todos en el buffe...  2019/08/19   
15  Very nice and quiet and clean rooms. \n We wil...  2019/08/19   
16  Rooms were clean, updated, and beds were comfo...  2019/08/19   
17  The staff was exceptionally helpful and the pr...  2019/08/19   
18  It was great for what we needed, a place to sl...  2019/08/19   
19  rooms were clean. we had two room and were abl...  2019/08/19   
20  A little off the beaten path, but ultimately p...  2019/08/18   
21  The room is tiny. The building is old and worn...  2019/08/18   
22  Awesome location, easy access to sights and su...  2019/08/18   
23  基本的に問題なしでした。\n 清潔で防音も普通な方で、水回りも清潔でシャワーの水圧も問題なし...  2019/08/18   
24  The room did not seem clean. There was some so...  2019/08/18   
25  Great location and friendly staff. Room with e...  2019/08/18   
26  Real nice love to go back soon \n I will recom...  2019/08/17   
27  Beautiful hotel. Friendly, helpful staff. Walk...  2019/08/17   
28  Beautiful Art Deco building, Foyer is very orn...  2019/08/17   
29  En general excelente. Fantástica situación\n D...  2019/08/17   
30  Really close to job interview. Nice morning br...  2019/08/17   
31  Les chambres familiales sont pratiques (nous é...  2019/08/17   
32  Rooms very dirty and aged. Breakfast was of po...  2019/08/17   
33                                                NaN  2019/08/17   
34  I have stayed for 5 nights, Great service, aff...  2019/08/17   

    polarity_scores  
0            0.9421  
1            0.8360  
2            0.6588  
3            0.3634  
4            0.9260  
5            0.8955  
6            0.0000  
7            0.7964  
8            0.7650  
9            0.5789  
10           0.8940  
11           0.8402  
12           0.5423  
13           0.7906  
14           0.4215  
15           0.6997  
16           0.7184  
17           0.7713  
18           0.5106  
19           0.5538  
20           0.9380  
21           0.6369  
22           0.7906  
23           0.0000  
24          -0.0665  
25           0.8074  
26           0.9118  
27           0.7579  
28           0.5994  
29          -0.2960  
30           0.7088  
31          -0.5550  
32          -0.8016  
33              NaN  
34              NaN

In [162]:
df.drop(['score'], axis=1 ,inplace=True)

In [170]:
res = {}
for i, row in tqdm(df.iterrows() , total= len(df)):
    review = row['Review']
    mydate = row['date']
    res[mydate] = sia().polarity_scores(review) 

  0%|          | 0/6393 [00:00<?, ?it/s]

In [174]:
vaders = pd.DataFrame(res).T

In [175]:
vaders.head()

neg    neu    pos  compound
2019/08/20  0.073  0.825  0.102    0.3634
2019/08/19  0.044  0.851  0.106    0.4556
2019/08/18  0.185  0.588  0.227    0.1280
2019/08/17  0.153  0.730  0.116   -0.1548
2019/08/16  0.043  0.772  0.185    0.7900

In [178]:
vaders = vaders.reset_index().rename(columns = {'index' : 'date'})
vaders = vaders.merge(df, how = 'left')

In [182]:
vaders.head()

date    neg    neu    pos  compound  \
0  2019/08/20  0.073  0.825  0.102    0.3634   
1  2019/08/20  0.073  0.825  0.102    0.3634   
2  2019/08/20  0.073  0.825  0.102    0.3634   
3  2019/08/20  0.073  0.825  0.102    0.3634   
4  2019/08/19  0.044  0.851  0.106    0.4556   

                                              Review  
0  I was very impressed with the resort.\n Great ...  
1  The rooms were nice the outside needs work als...  
2  Great location! I have stayed at this hotel on...  
3  The hotel was adequate for my stay. The strips...  
4  Great location, room was large and spacious. P...

In [185]:
vaders['score']= vaders['compound'].apply(lambda c: 'positive' if c >=0 else 'negative')

In [186]:
vaders.head()

date    neg    neu    pos  compound  \
0  2019/08/20  0.073  0.825  0.102    0.3634   
1  2019/08/20  0.073  0.825  0.102    0.3634   
2  2019/08/20  0.073  0.825  0.102    0.3634   
3  2019/08/20  0.073  0.825  0.102    0.3634   
4  2019/08/19  0.044  0.851  0.106    0.4556   

                                              Review     score  
0  I was very impressed with the resort.\n Great ...  positive  
1  The rooms were nice the outside needs work als...  positive  
2  Great location! I have stayed at this hotel on...  positive  
3  The hotel was adequate for my stay. The strips...  positive  
4  Great location, room was large and spacious. P...  positive

In [190]:
vaders['score'].value_counts()

positive    4915
negative    1478
Name: score, dtype: int64

 there are 4915 positive comments and 1478 negative comments

In [191]:
vaders['date'].value_counts()

Jun 2019      145
May 2019      121
Jul 2019       92
2018/12/01     66
Oct 2018       58
             ... 
2019/2/14       3
Dec 2018        2
2019/06/06      2
2019/06/08      2
2019/05/31      2
Name: date, Length: 403, dtype: int64

highest numbers reviews are on june 2019

In [284]:
vaders.groupby(['date'], as_index = False)['score'].value_counts().sort_values(by = 'count', ascending = False)

date     score  count
397    Jun 2019  positive    145
399    May 2019  negative    121
396    Jul 2019  positive     92
122  2018/12/01  positive     66
401    Oct 2018  positive     58
..          ...       ...    ...
269  2019/06/14  positive      3
393    Dec 2018  negative      2
255  2019/05/31  positive      2
261  2019/06/06  negative      2
263  2019/06/08  positive      2

[403 rows x 3 columns]

In [283]:
vaders.groupby(['date'], as_index = False)['score'].value_counts().sort_values(by = 'count')

date     score  count
261  2019/06/06  negative      2
393    Dec 2018  negative      2
255  2019/05/31  positive      2
263  2019/06/08  positive      2
269  2019/06/14  positive      3
..          ...       ...    ...
401    Oct 2018  positive     58
122  2018/12/01  positive     66
396    Jul 2019  positive     92
399    May 2019  negative    121
397    Jun 2019  positive    145

[403 rows x 3 columns]

highest positive review are on june 2019  and highest negative are on may 2019